sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: "3.6"
      env: TOXENV=lint
    - if: tag IS present
      python: "3.6"
      env:
        - TWINE_USERNAME=qiskit
      install: pip install -U twine
      script:
        - python3 setup.py sdist bdist_wheel
        - twine upload dist/qiskit*
cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox
language: python
script:
  - tox
notifications:
  email: false
