# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- stable

jobs:
  - job: 'Windows_Testing'
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
          TOXENV: py35
          imageName: "vs2017-win2016"
        Python36:
          python.version: '3.6'
          TOXENV: py36
          imageName: "vs2017-win2016"
        Python37:
          python.version: '3.7'
          TOXENV: py37
        Python38:
          python.version: '3.8'
          TOXENV: py38
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
      - bash: |
          set -e
          python -m pip install --upgrade pip
          pip install tox
        displayName: 'Install job dependencies'
      - script: tox -e%TOXENV%
        displayName: 'Install package/test dependencies and run tests'

  - job: 'macOS_Testing'
    strategy:
      matrix:
        Python35:
          python.version: '3.5'
          TOXENV: py35
        Python36:
          python.version: '3.6'
          TOXENV: py36
        Python37:
          python.version: '3.7'
          TOXENV: py37
        Python38:
          python.version: '3.8'
          TOXENV: py38
    pool:
      vmImage: "macOS-10.13"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'
      - bash: |
          set -e
          python -m pip install --upgrade pip
          pip install tox
        displayName: 'Install job dependencies'
      - script: tox -e$TOXENV
        displayName: 'Install package/test dependencies and run tests'
